import React, { useState } from 'react';
import Input from '../common/Input';
import Select from '../common/Select';
import Button from '../common/Button';
import { Sparkles } from 'lucide-react';

export default function AIQuestionGenerator({ onGenerateDraft }) {
  const [topic, setTopic] = useState('Two Pointers');
  const [difficulty, setDifficulty] = useState('easy');
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    setLoading(true);
    setTimeout(() => {
      onGenerateDraft?.({
        topic,
        difficulty,
        prompt: 'Draft generated by Gemini: Given an array of integers, remove duplicates in-place such that each unique element appears only once.',
        status: 'draft'
      });
      setLoading(false);
    }, 1000);
  };

  return (
    <div className="p-5 bg-gradient-to-br from-indigo-50 to-white border border-indigo-200 rounded-2xl space-y-4">
      <div className="flex items-center gap-2 text-indigo-900 font-bold text-sm">
        <Sparkles size={18} />
        <span>Gemini AI Question Generator (Bounded Drafts)</span>
      </div>
      <p className="text-xs text-indigo-700">Generates draft questions for admin review and approval before persisting to Supabase.</p>
      <div className="grid grid-cols-2 gap-3">
        <Input label="Topic Focus" value={topic} onChange={e => setTopic(e.target.value)} />
        <Select label="Difficulty" options={['easy', 'medium', 'hard']} value={difficulty} onChange={e => setDifficulty(e.target.value)} />
      </div>
      <Button variant="primary" size="sm" onClick={handleGenerate} disabled={loading}>
        {loading ? 'Generating with Gemini...' : 'Generate Candidate Draft'}
      </Button>
    </div>
  );
}
