const n8nClient = require('../integrations/n8nClient');
const geminiClient = require('../integrations/geminiClient');

class AIService {
  async analyzeAssessment(context) {
    return await n8nClient.triggerWorkflow('/assessment-analysis', context);
  }
  async explainConcept(prompt, context) {
    return await geminiClient.generateGuidance(prompt, context);
  }
  async generateQuestionDraft(criteria) {
    return {
      draft_id: 'draft_' + Date.now(),
      topic: criteria.topic,
      difficulty: criteria.difficulty,
      prompt: 'Draft question generated by Gemini for review: Find longest palindromic substring.',
      status: 'pending_approval'
    };
  }
}
module.exports = new AIService();
